import { app } from "electron"
import { mkdir, readFile, writeFile, appendFile } from "fs/promises"
import path from "path"
import { dataDirName } from "../../config/system-name"
import * as settingsService from "../../settings/service"
import {
  createCompletion,
  resolveLlm,
  NoActiveProviderError,
  type LlmSelection,
} from "../providers"

const STALE_LOCK_MS = 5 * 60 * 1000
const MEMORY_MAX_OUTPUT_TOKENS = 1500
const INACTIVITY_BOUNDARY_MS = 45 * 60 * 1000
const STAGING_RECORD_BOUNDARY = 20
const STAGING_BYTE_BOUNDARY = 24 * 1024

type MemoryCategory = "identity" | "preferences" | "knowledge" | "lessons"

interface MemoryState {
  lastConversationId: string | null
  lastRecentDir: string | null
  lastTurnAt: string | null
  lastSwapTime: string | null
  swapInProgress: boolean
}

export interface RecordTurnInput {
  conversationId: string
  userText: string
  assistantText: string
  workspaceDir?: string
}

const CATEGORY_HEADINGS: Record<MemoryCategory, string> = {
  identity: "User Identity",
  preferences: "Interaction Preferences & Rules",
  knowledge: "Workspace Domain Knowledge",
  lessons: "Lessons & Insights",
}

const CATEGORY_DESCRIPTIONS: Record<MemoryCategory, string> = {
  identity: "User identity information. Load when personal/user facts matter.",
  preferences:
    "Interaction preferences and behavioral rules. Load when adapting responses to the user's preferred style, formats, or constraints.",
  knowledge:
    "Workspace-specific domain knowledge. Load when project, product, business, workflow, architecture, or repo facts may affect the task.",
  lessons:
    "Workspace-specific lessons and insights. Load when prior failures, gotchas, or decisions may affect the task.",
}

function globalSkillsDir(): string {
  return path.join(app.getPath("home"), dataDirName(), "skills")
}

function workspaceSkillsDir(workspaceDir: string): string {
  return path.join(workspaceDir, dataDirName(), "skills")
}

function stateFile(): string {
  return path.join(app.getPath("userData"), "memory-state.json")
}

function recentDirFor(workspaceDir?: string): string {
  return path.join(
    workspaceDir ? workspaceSkillsDir(workspaceDir) : globalSkillsDir(),
    "memory-recent"
  )
}

function categorySkillPath(
  category: MemoryCategory,
  workspaceDir?: string
): string {
  const global = category === "identity" || category === "preferences"
  const root =
    global || !workspaceDir
      ? globalSkillsDir()
      : workspaceSkillsDir(workspaceDir)
  return path.join(root, `memory-${category}`, "SKILL.md")
}

function recentSkillPath(workspaceDir?: string): string {
  return path.join(recentDirFor(workspaceDir), "SKILL.md")
}

function stagingPathFromRecentDir(recentDir: string): string {
  return path.join(recentDir, "staging.md")
}

function refDirFromRecentDir(recentDir: string): string {
  return path.join(recentDir, "reference")
}

async function readText(file: string): Promise<string> {
  try {
    return await readFile(file, "utf-8")
  } catch {
    return ""
  }
}

async function writeIfMissing(file: string, content: string): Promise<void> {
  const existing = await readText(file)
  if (existing) return
  await mkdir(path.dirname(file), { recursive: true })
  await writeFile(file, content, "utf-8")
}

function skillScaffold(category: MemoryCategory): string {
  return `---
name: memory-${category}
description: |
  ${CATEGORY_DESCRIPTIONS[category]}
metadata:
  managed-by: memory
---

# ${CATEGORY_HEADINGS[category]}

<!-- Do NOT edit this file directly! Memory is maintained automatically by a dedicated background service. Direct edits can cause duplicates and conflicts. -->
`
}

function recentScaffold(): string {
  return `---
name: memory-recent
description: |
  Recent session memory. Load when the user mentions "last time", "previously", "earlier", or asks recall questions like "do you know/remember X".
  Grep the reference/ directory for raw details.
  Currently 0 records.
metadata:
  managed-by: memory
---

# Recent Session Memory
`
}

async function ensureGlobalMemorySkills(): Promise<void> {
  await Promise.all([
    writeIfMissing(categorySkillPath("identity"), skillScaffold("identity")),
    writeIfMissing(
      categorySkillPath("preferences"),
      skillScaffold("preferences")
    ),
  ])
}

async function ensureWorkspaceMemorySkills(
  workspaceDir?: string
): Promise<void> {
  if (workspaceDir) {
    await appendWorkspaceGitignore(workspaceDir)
    await Promise.all([
      writeIfMissing(
        categorySkillPath("knowledge", workspaceDir),
        skillScaffold("knowledge")
      ),
      writeIfMissing(
        categorySkillPath("lessons", workspaceDir),
        skillScaffold("lessons")
      ),
      writeIfMissing(recentSkillPath(workspaceDir), recentScaffold()),
    ])
    return
  }
  await writeIfMissing(recentSkillPath(), recentScaffold())
}

async function appendWorkspaceGitignore(workspaceDir: string): Promise<void> {
  const file = path.join(workspaceDir, ".gitignore")
  const rule = `${dataDirName()}/skills/memory-*`
  const content = await readText(file)
  const hasRule = content
    .split(/\r?\n/)
    .map((line) => line.trim())
    .includes(rule)
  if (hasRule) return
  const prefix = content && !content.endsWith("\n") ? "\n" : ""
  await appendFile(file, `${prefix}${rule}\n`, "utf-8")
}

async function loadState(): Promise<MemoryState> {
  const raw = await readText(stateFile())
  if (!raw) {
    return {
      lastConversationId: null,
      lastRecentDir: null,
      lastTurnAt: null,
      lastSwapTime: null,
      swapInProgress: false,
    }
  }
  try {
    const parsed = JSON.parse(raw) as Partial<MemoryState>
    return {
      lastConversationId:
        typeof parsed.lastConversationId === "string"
          ? parsed.lastConversationId
          : null,
      lastRecentDir:
        typeof parsed.lastRecentDir === "string" ? parsed.lastRecentDir : null,
      lastTurnAt:
        typeof parsed.lastTurnAt === "string" ? parsed.lastTurnAt : null,
      lastSwapTime:
        typeof parsed.lastSwapTime === "string" ? parsed.lastSwapTime : null,
      swapInProgress: parsed.swapInProgress === true,
    }
  } catch {
    return {
      lastConversationId: null,
      lastRecentDir: null,
      lastTurnAt: null,
      lastSwapTime: null,
      swapInProgress: false,
    }
  }
}

function stagingRecordCount(staging: string): number {
  return (staging.match(/^### /gm) ?? []).length
}

async function shouldPromoteBeforeAppend(
  state: MemoryState,
  currentConversationId: string,
  currentRecentDir: string
): Promise<boolean> {
  if (!state.lastRecentDir) return false
  const staging = (
    await readText(stagingPathFromRecentDir(state.lastRecentDir))
  ).trim()
  if (!staging) return false

  const conversationChanged =
    !!state.lastConversationId &&
    state.lastConversationId !== currentConversationId
  const scopeChanged = state.lastRecentDir !== currentRecentDir
  const lastTurnAt = state.lastTurnAt
    ? new Date(state.lastTurnAt).getTime()
    : Number.NaN
  const inactive =
    Number.isFinite(lastTurnAt) &&
    Date.now() - lastTurnAt >= INACTIVITY_BOUNDARY_MS
  const tooManyRecords = stagingRecordCount(staging) >= STAGING_RECORD_BOUNDARY
  const tooLarge = Buffer.byteLength(staging, "utf-8") >= STAGING_BYTE_BOUNDARY

  return (
    conversationChanged ||
    scopeChanged ||
    inactive ||
    tooManyRecords ||
    tooLarge
  )
}

async function saveState(state: MemoryState): Promise<void> {
  await mkdir(path.dirname(stateFile()), { recursive: true })
  await writeFile(stateFile(), JSON.stringify(state, null, 2), "utf-8")
}

function resolveMemorySelection(): LlmSelection {
  const memory = settingsService.getMemory()
  return { accountId: memory.accountId, modelId: memory.modelId }
}

async function memoryComplete(
  prompt: string,
  maxOutputTokens = MEMORY_MAX_OUTPUT_TOKENS
): Promise<string | undefined> {
  try {
    const { client, model, apiMode } = resolveLlm(resolveMemorySelection())
    const res = await createCompletion(
      client,
      model,
      maxOutputTokens,
      {
        messages: [
          {
            role: "system",
            content:
              "You maintain long-term memory files for an AI agent. Return only the requested structured output.",
          },
          { role: "user", content: prompt },
        ],
      },
      [],
      apiMode
    )
    return contentToText((res as any).choices?.[0]?.message?.content).trim()
  } catch (err) {
    if (err instanceof NoActiveProviderError) {
      console.warn(`[memory] skipped: ${err.message}`)
      return undefined
    }
    console.warn("[memory] LLM call failed:", err)
    return undefined
  }
}

function contentToText(content: unknown): string {
  if (typeof content === "string") return content
  if (Array.isArray(content)) {
    return content
      .map((part: any) =>
        typeof part === "string" ? part : (part?.text ?? "")
      )
      .join("")
  }
  return ""
}

function parseJsonObject(text: string | undefined): Record<string, unknown> {
  if (!text) return {}
  const fenced = /```(?:json)?\s*([\s\S]*?)\s*```/i.exec(text)
  const raw = (fenced?.[1] ?? text).trim()
  try {
    const parsed = JSON.parse(raw)
    return parsed && typeof parsed === "object" && !Array.isArray(parsed)
      ? (parsed as Record<string, unknown>)
      : {}
  } catch {
    return {}
  }
}

function parseFrontmatter(content: string): {
  frontmatter: string
  body: string
} {
  const match = /^(---\n[\s\S]*?\n---\n?)([\s\S]*)$/.exec(content)
  if (!match) return { frontmatter: "", body: content }
  return { frontmatter: match[1], body: match[2] }
}

function existingItems(content: string): string[] {
  const { body } = parseFrontmatter(content)
  return (
    body
      .replace(/<!--[\s\S]*?-->/g, "")
      .match(/^- .+/gm)
      ?.map((line) => line.slice(2).trim())
      .filter(Boolean) ?? []
  )
}

function extractKeywords(summaryText: string): string[] {
  const keywords = new Set<string>()
  const lines = summaryText.match(/^- .+/gm) ?? []
  for (const line of lines) {
    const terms =
      line.match(
        /[\u4e00-\u9fff]{2,}|[A-Z][a-zA-Z0-9]+(?:\s+[A-Z][a-zA-Z0-9]+)*/g
      ) ?? []
    for (const term of terms.slice(0, 3)) keywords.add(term)
  }
  return [...keywords].slice(0, 15)
}

function buildRecentFrontmatter(
  keywords: string[],
  recordCount: number
): string {
  const kw = keywords.length ? ` ${keywords.join(", ")}.` : ""
  return `---
name: memory-recent
description: |
  Recent session memory: summaries and key context from the last session.
  Load this skill when the user mentions "last time", "previously", "earlier", or asks recall questions like "do you know/remember X".
  Grep the reference/ directory for raw details.
  Keywords: recent session, last time, previously, recall.${kw}
  Currently ${recordCount} records.
metadata:
  managed-by: memory
---
`
}

async function appendSessionLog(
  recentDir: string,
  userText: string,
  assistantText: string
): Promise<void> {
  const now = new Date()
  const date = now.toISOString().slice(0, 10)
  const time = now.toTimeString().slice(0, 5)
  const refDir = refDirFromRecentDir(recentDir)
  await mkdir(refDir, { recursive: true })
  await appendFile(
    path.join(refDir, `${date}.md`),
    `## [${time}]\n\n**User**: ${userText.slice(0, 1000)}\n\n**Assistant**: ${assistantText.slice(0, 1500)}\n\n---\n\n`,
    "utf-8"
  )
}

async function appendTurnSummary(
  recentDir: string,
  userText: string,
  assistantText: string
): Promise<void> {
  const time = new Date().toTimeString().slice(0, 5)
  const summary = await memoryComplete(
    `Extract durable facts stated by the user from the following exchange.

User:
${userText.slice(0, 1200)}

Assistant:
${assistantText.slice(0, 800)}

Extract only facts useful in future conversations.

## Extract
- Identity: name, role, location, team, durable personal facts
- Tools/processes/domain: software, platforms, workflows, formulas, methods, project/repo/business facts
- Preferences: user instructions about assistant behavior, format, tone, language, rigor
- Lessons: failures, gotchas, hard-won insights, decisions with consequences

## Do not extract
- The user's questions or requests
- Assistant suggestions, calculations, or invented facts
- Small talk

Rules:
1. Preserve specific names, paths, products, and numbers.
2. One item = one independent fact.
3. If the user stated no durable facts, output an empty section with no bullets.

Format exactly:
### ${time} - [short title]
- [fact 1]
- [fact 2]`,
    700
  )
  if (!summary) return
  await mkdir(recentDir, { recursive: true })
  await appendFile(
    stagingPathFromRecentDir(recentDir),
    `\n${summary}\n`,
    "utf-8"
  )
}

async function performSwap(
  recentDir: string,
  state: MemoryState
): Promise<void> {
  state.swapInProgress = true
  state.lastSwapTime = new Date().toISOString()
  await saveState(state)

  try {
    const stagingFile = stagingPathFromRecentDir(recentDir)
    const staging = (await readText(stagingFile)).trim()
    if (!staging) return

    await writeFile(stagingFile, "", "utf-8")
    void classifyAndDistribute(staging, recentDir).catch((err) =>
      console.warn("[memory] classification failed:", err)
    )

    const keywords = extractKeywords(staging)
    const recordCount = stagingRecordCount(staging)
    const body = `\n# Recent Session Memory\n\n## ${new Date()
      .toISOString()
      .slice(0, 10)}\n\n${staging}\n`
    await writeFile(
      path.join(recentDir, "SKILL.md"),
      buildRecentFrontmatter(keywords, recordCount) + body,
      "utf-8"
    )
  } finally {
    state.swapInProgress = false
    state.lastSwapTime = new Date().toISOString()
    await saveState(state)
  }
}

async function classifyAndDistribute(
  summaryContent: string,
  recentDir: string
): Promise<void> {
  const facts =
    summaryContent
      .match(/^- .+/gm)
      ?.map((line) => line.slice(2).trim())
      .filter(Boolean) ?? []
  if (facts.length === 0) return

  const workspaceDir = workspaceFromRecentDir(recentDir)
  const result = await memoryComplete(
    `Classify each fact into exactly one category.

Categories:
- identity: objective facts about the user
- preferences: instructions for assistant behavior, tone, format, language, rigor
- knowledge: workspace/project/business/domain/tools/process facts
- lessons: failures, gotchas, lessons learned, decisions with consequences

Facts:
${facts.map((fact) => `- ${fact}`).join("\n")}

Return JSON only:
{
  "identity": ["..."],
  "preferences": ["..."],
  "knowledge": ["..."],
  "lessons": ["..."]
}`,
    1200
  )
  const classified = parseJsonObject(result)
  await Promise.all(
    (["identity", "preferences", "knowledge", "lessons"] as MemoryCategory[])
      .map((category) => ({
        category,
        facts: classified[category],
      }))
      .filter(
        (entry): entry is { category: MemoryCategory; facts: string[] } =>
          Array.isArray(entry.facts) && entry.facts.length > 0
      )
      .map(({ category, facts }) =>
        editCategorySkill(category, facts, workspaceDir)
      )
  )
}

function workspaceFromRecentDir(recentDir: string): string | undefined {
  if (recentDir === path.join(globalSkillsDir(), "memory-recent")) {
    return undefined
  }
  const suffix = path.join(dataDirName(), "skills", "memory-recent")
  return recentDir.endsWith(suffix)
    ? recentDir.slice(0, -suffix.length).replace(/[\\/]$/, "")
    : undefined
}

async function editCategorySkill(
  category: MemoryCategory,
  newFacts: string[],
  workspaceDir?: string
): Promise<void> {
  const file = categorySkillPath(category, workspaceDir)
  await writeIfMissing(file, skillScaffold(category))
  const current = await readText(file)
  const currentItems = existingItems(current)
  const heading = CATEGORY_HEADINGS[category]
  const result = await memoryComplete(
    `Merge new facts into the "${heading}" memory category.

Existing memory:
${currentItems.length ? currentItems.map((i) => `- ${i}`).join("\n") : "(none)"}

New facts:
${newFacts.map((fact) => `- ${fact}`).join("\n")}

Editing rules:
1. Merge new facts into the existing list.
2. Deduplicate semantically identical items; keep the more complete version.
3. If old and new facts conflict, keep the newer fact.
4. Do not delete unrelated existing items.
5. Each memory item should be one complete sentence.

Return JSON only:
{
  "items": ["merged item 1"],
  "description": "${heading}. Currently N records, covering: xxx. Keep under 200 chars."
}`,
    1200
  )
  const parsed = parseJsonObject(result)
  const items = parsed.items
  if (!Array.isArray(items) || items.length === 0) return
  const merged = items
    .map(String)
    .map((item) => item.trim())
    .filter(Boolean)
  if (merged.length < currentItems.length - 2 && currentItems.length > 0) return

  const description =
    typeof parsed.description === "string" && parsed.description.trim()
      ? parsed.description.trim()
      : `${heading}. Currently ${merged.length} records.`
  const body =
    `\n# ${heading}\n\n` +
    "<!-- Do NOT edit this file directly! Memory is maintained automatically by a dedicated background service. Direct edits can cause duplicates and conflicts. -->\n" +
    merged.map((item) => `- ${item}`).join("\n") +
    "\n"
  await writeFile(
    file,
    `---\nname: memory-${category}\ndescription: |\n  ${description}\nmetadata:\n  managed-by: memory\n---\n${body}`,
    "utf-8"
  )
}

export async function recordMemoryTurn(input: RecordTurnInput): Promise<void> {
  const settings = settingsService.getMemory()
  if (!settings.enabled) return
  await ensureGlobalMemorySkills()
  await ensureWorkspaceMemorySkills(input.workspaceDir)

  const recentDir = recentDirFor(input.workspaceDir)
  const state = await loadState()
  const isStale =
    state.swapInProgress &&
    state.lastSwapTime &&
    Date.now() - new Date(state.lastSwapTime).getTime() > STALE_LOCK_MS
  const previousRecentDir = state.lastRecentDir
  if (
    previousRecentDir &&
    (!state.swapInProgress || isStale) &&
    (await shouldPromoteBeforeAppend(state, input.conversationId, recentDir))
  ) {
    await performSwap(previousRecentDir, state).catch((err) =>
      console.warn("[memory] swap failed:", err)
    )
  }

  state.lastConversationId = input.conversationId
  state.lastRecentDir = recentDir
  state.lastTurnAt = new Date().toISOString()
  await saveState(state)

  await appendSessionLog(recentDir, input.userText, input.assistantText).catch(
    (err) => console.warn("[memory] log append failed:", err)
  )
  await appendTurnSummary(recentDir, input.userText, input.assistantText).catch(
    (err) => console.warn("[memory] extraction failed:", err)
  )
}

export async function reconcilePendingMemoryOnStartup(): Promise<void> {
  if (!settingsService.getMemory().enabled) return
  const state = await loadState()
  if (!state.lastRecentDir) return

  const isStale =
    state.swapInProgress &&
    state.lastSwapTime &&
    Date.now() - new Date(state.lastSwapTime).getTime() > STALE_LOCK_MS
  if (state.swapInProgress && !isStale) return

  await ensureGlobalMemorySkills()
  await performSwap(state.lastRecentDir, state).catch((err) =>
    console.warn("[memory] startup reconcile failed:", err)
  )
}
