import path from "path"
import type {
  Evidence,
  FindingConfidence,
} from "../../../shared/mission-control/workspace-analysis"
import type { ProjectRoot, Reader } from "./inventory"
import { RECIPES, type RecipeContext } from "./recipes"

// Stage 4 (plan 106.11): files a project generates rather than writes by
// hand, paired with the command that regenerates them, so parallel stories
// regenerate on merge instead of hand-merging (or conflicting on) them.
// Globs and commands are workspace-relative, as GeneratedFilesRule is applied
// (the merge queue runs the command from the workspace directory).

export interface GeneratedGroup {
  key: string
  // What produces them, for the title: "protobuf", "Prisma client", "pnpm lockfile".
  label: string
  root: string
  paths: string[]
  command: string | null
  confidence: FindingConfidence
  evidence: Omit<Evidence, "id">[]
  // A prerequisite the command needs (a running database).
  needs?: string
  lockfile?: boolean
}

export interface GeneratedInput {
  tracked: string[]
  roots: ProjectRoot[]
  read: Reader
  // Newest first; workspace-relative paths per commit.
  history: string[][]
  // Recipe contexts per root dir, for lock regeneration commands.
  contexts: Map<string, RecipeContext>
}

const HEADER_BYTES = 800
const MAX_HEADER_SCANS = 4000

// Strong markers are tool conventions; weak ones are prose a person might
// write in a hand-maintained file, so they only make a finding "likely".
const MARKERS: Array<{ re: RegExp; label: string; strong: boolean }> = [
  {
    re: /Code generated .* DO NOT EDIT\./,
    label: "Go generated-code marker",
    strong: true,
  },
  {
    re: /GENERATED CODE - DO NOT MODIFY BY HAND/,
    label: "Dart build_runner marker",
    strong: true,
  },
  {
    re: /<auto-generated[\s>]/i,
    label: "C# <auto-generated> marker",
    strong: true,
  },
  {
    re: /autogenerated by (pip-compile|uv)/i,
    label: "pip-compile header",
    strong: true,
  },
  { re: /@generated\b/, label: "@generated marker", strong: true },
  // JSON can't carry a comment; generators record themselves in fields.
  {
    re: /"(generator|generator_?[vV]ersion|generated_?[bB]y|generated_?[aA]t|generated_?[wW]ith)"\s*:/,
    label: "generator metadata",
    strong: false,
  },
  { re: /\bDO NOT EDIT\b/, label: "DO NOT EDIT header", strong: false },
  {
    re: /\b(auto[- ]?generated|automatically generated|this file (is|was) generated)\b/i,
    label: "auto-generated header",
    strong: false,
  },
]

// Known generated suffixes and the tool behind them.
const SUFFIXES: Array<{
  re: RegExp
  glob: string
  label: string
  tool: string
}> = [
  {
    re: /\.g\.dart$/,
    glob: "**/*.g.dart",
    label: "Dart build_runner",
    tool: "build_runner",
  },
  {
    re: /\.freezed\.dart$/,
    glob: "**/*.freezed.dart",
    label: "Dart build_runner",
    tool: "build_runner",
  },
  {
    re: /\.mocks\.dart$/,
    glob: "**/*.mocks.dart",
    label: "Dart build_runner",
    tool: "build_runner",
  },
  {
    re: /\.gr\.dart$/,
    glob: "**/*.gr.dart",
    label: "Dart build_runner",
    tool: "build_runner",
  },
  {
    re: /_pb2(_grpc)?\.pyi?$/,
    glob: "**/*_pb2*.py*",
    label: "protobuf (Python)",
    tool: "protobuf",
  },
  {
    re: /\.pb\.go$/,
    glob: "**/*.pb.go",
    label: "protobuf (Go)",
    tool: "protobuf",
  },
  {
    re: /\.pb\.swift$/,
    glob: "**/*.pb.swift",
    label: "protobuf (Swift)",
    tool: "protobuf",
  },
  {
    re: /\.pb\.(cc|h)$/,
    glob: "**/*.pb.*",
    label: "protobuf (C++)",
    tool: "protobuf",
  },
  {
    re: /\.Designer\.cs$/,
    glob: "**/*.Designer.cs",
    label: "C# designer files",
    tool: "dotnet",
  },
  {
    re: /\.g\.(i\.)?cs$/,
    glob: "**/*.g.cs",
    label: "C# source generators",
    tool: "dotnet",
  },
  {
    re: /(^|\/)routeTree\.gen\.ts$/,
    glob: "**/routeTree.gen.ts",
    label: "TanStack Router route tree",
    tool: "tsr",
  },
  {
    re: /(^|\/)next-env\.d\.ts$/,
    glob: "next-env.d.ts",
    label: "Next.js types",
    tool: "next",
  },
]

const TEXT_EXT =
  /\.(ts|tsx|js|jsx|mjs|cjs|py|pyi|go|rs|java|kt|kts|cs|swift|m|h|hpp|hh|c|cc|cpp|cxx|php|rb|rbi|dart|sql|graphql|gql|proto|json|ya?ml|toml|txt)$/

function under(root: string, file: string) {
  return !root || file === root || file.startsWith(`${root}/`)
}
function rootFor(roots: ProjectRoot[], file: string): string {
  return (
    roots
      .map((r) => r.dir)
      .filter((dir) => under(dir, file))
      .sort((a, b) => b.length - a.length)[0] ?? ""
  )
}
// Run a command from the workspace directory in `root`.
export function inRoot(root: string, command: string) {
  return root ? `cd ${root} && ${command}` : command
}

function scripts(pkg: string | null): Record<string, string> {
  if (!pkg) return {}
  try {
    const json = JSON.parse(pkg) as { scripts?: Record<string, string> }
    return json.scripts ?? {}
  } catch {
    return {}
  }
}

function runner(root: ProjectRoot): string {
  const e = root.ecosystems
  return e.includes("pnpm")
    ? "pnpm run"
    : e.includes("yarn")
      ? "yarn run"
      : e.includes("bun")
        ? "bun run"
        : "npm run"
}

function makeTargets(makefile: string | null): string[] {
  if (!makefile) return []
  return [...makefile.matchAll(/^([A-Za-z0-9_.-]+)\s*:(?!=)/gm)].map(
    (m) => m[1]
  )
}

const GENERATOR_SCRIPT =
  /^(gen|generate|codegen|proto|protos|openapi|graphql|prisma|sqlc|swiftgen|build_runner)([:_-].*)?$|(^|[:_-])(gen|generate|codegen)$/i

// Tool invocations in a script body, for pairing outputs with scripts.
const TOOL_IN_SCRIPT: Array<{ re: RegExp; tool: string }> = [
  { re: /\bprisma\s+generate\b/, tool: "prisma" },
  { re: /\bgraphql-codegen\b|\bgql-gen\b/, tool: "graphql-codegen" },
  {
    re: /\bopenapi-generator(-cli)?\b|\bopenapi-typescript\b|\borval\b|\bkubb\b/,
    tool: "openapi",
  },
  { re: /\bbuf\s+generate\b|\bprotoc\b/, tool: "protobuf" },
  { re: /\bsqlc\s+generate\b/, tool: "sqlc" },
  { re: /\btsr\s+generate\b/, tool: "tsr" },
  { re: /\bbuild_runner\b/, tool: "build_runner" },
  { re: /\bswiftgen\b/, tool: "swiftgen" },
  { re: /\bsourcery\b/, tool: "sourcery" },
  { re: /\bdrizzle-kit\s+generate\b/, tool: "drizzle" },
]

interface ToolConfig {
  tool: string
  label: string
  root: string
  // The config file (workspace-relative), for co-change pairing.
  file: string
  outputs: string[]
  command: string | null
  needs?: string
  // A package script, Makefile target, or build task rather than a config
  // that declares its outputs.
  fromScript?: boolean
  // A pre-commit hook that runs on every commit (always_run): its outputs
  // change in lock-step with most commits.
  everyCommit?: boolean
}

// Local pre-commit hooks that look like generators (an index, codegen, a
// lockfile or schema refresh), not linters: `repo: local`, not fed the staged
// file names, and named for what they produce.
function preCommitGenerators(text: string): Array<{
  id: string
  name: string | null
  entry: string
  alwaysRun: boolean
}> {
  const out: Array<{
    id: string
    name: string | null
    entry: string
    alwaysRun: boolean
  }> = []
  const repos = text.split(/^\s*-\s*repo:\s*/m).slice(1)
  for (const repo of repos) {
    if (!/^local\b/.test(repo.trim())) continue
    for (const hook of repo.split(/^\s*-\s*id:\s*/m).slice(1)) {
      const id = hook
        .split("\n")[0]
        .trim()
        .replace(/^["']|["']$/g, "")
      const field = (name: string) =>
        new RegExp(`^\\s*${name}:\\s*(.+)$`, "m")
          .exec(hook)?.[1]
          .trim()
          .replace(/^["']|["']$/g, "") ?? null
      const entry = field("entry")
      if (!entry) continue
      const passFilenames = field("pass_filenames") !== "false"
      const name = field("name")
      const generator =
        /index|gen|generate|codegen|build|refresh|update|sync|lock|compile|schema|snapshot|manifest/i.test(
          `${id} ${name ?? ""}`
        )
      if (passFilenames || !generator) continue
      out.push({ id, name, entry, alwaysRun: field("always_run") === "true" })
    }
  }
  return out
}

async function toolConfigs(input: GeneratedInput): Promise<ToolConfig[]> {
  const out: ToolConfig[] = []
  const tracked = new Set(input.tracked)
  for (const root of input.roots) {
    const at = (name: string) => path.posix.join(root.dir, name)
    const pkg = root.files.includes("package.json")
      ? await input.read(at("package.json"))
      : null
    const s = scripts(pkg)
    const scriptFor = (tool: string) => {
      const entry = Object.entries(s).find(([, body]) =>
        TOOL_IN_SCRIPT.some((t) => t.tool === tool && t.re.test(body))
      )
      return entry ? `${runner(root)} ${entry[0]}` : null
    }
    const rel = (p: string) =>
      path.posix
        .normalize(path.posix.join(root.dir, p))
        .replace(/^\.\//, "")
        .replace(/\/$/, "")
    // Prisma: generator output path.
    for (const file of input.tracked.filter(
      (f) => under(root.dir, f) && /(^|\/)schema\.prisma$/.test(f)
    )) {
      const text = (await input.read(file)) ?? ""
      const output = /generator\s+\w+\s*\{[^}]*output\s*=\s*"([^"]+)"/.exec(
        text
      )?.[1]
      const outputs = output
        ? [
            path.posix.normalize(
              path.posix.join(path.posix.dirname(file), output)
            ),
          ]
        : []
      out.push({
        tool: "prisma",
        label: "Prisma client",
        root: root.dir,
        file,
        outputs,
        command: scriptFor("prisma") ?? "npx prisma generate",
      })
    }
    // GraphQL Code Generator.
    for (const name of [
      "codegen.yml",
      "codegen.yaml",
      "codegen.ts",
      "codegen.json",
      ".graphqlrc.yml",
    ]) {
      if (!tracked.has(at(name))) continue
      const text = (await input.read(at(name))) ?? ""
      const outputs = [
        ...text.matchAll(
          /^\s{2}["']?([\w./@-]+\.(?:ts|tsx|js|graphql|json)|[\w./@-]+\/)["']?\s*:/gm
        ),
        ...text.matchAll(
          /["']([\w./@-]+\.(?:ts|tsx)|[\w./@-]+\/)["']\s*:\s*\{/g
        ),
      ].map((m) => rel(m[1]))
      out.push({
        tool: "graphql-codegen",
        label: "GraphQL Code Generator",
        root: root.dir,
        file: at(name),
        outputs: [...new Set(outputs)],
        command: scriptFor("graphql-codegen") ?? "npx graphql-codegen",
      })
    }
    // buf.
    for (const name of ["buf.gen.yaml", "buf.gen.yml"]) {
      if (!tracked.has(at(name))) continue
      const text = (await input.read(at(name))) ?? ""
      const outputs = [...text.matchAll(/^\s*out:\s*["']?([^\s"'#]+)/gm)].map(
        (m) => rel(m[1])
      )
      out.push({
        tool: "protobuf",
        label: "protobuf (buf)",
        root: root.dir,
        file: at(name),
        outputs: [...new Set(outputs)],
        command: scriptFor("protobuf") ?? "buf generate",
      })
    }
    // sqlc.
    for (const name of ["sqlc.yaml", "sqlc.yml", "sqlc.json"]) {
      if (!tracked.has(at(name))) continue
      const text = (await input.read(at(name))) ?? ""
      const outputs = [...text.matchAll(/^\s*out:\s*["']?([^\s"'#]+)/gm)].map(
        (m) => rel(m[1])
      )
      out.push({
        tool: "sqlc",
        label: "sqlc",
        root: root.dir,
        file: at(name),
        outputs: [...new Set(outputs)],
        command: "sqlc generate",
      })
    }
    // SwiftGen.
    if (tracked.has(at("swiftgen.yml"))) {
      const text = (await input.read(at("swiftgen.yml"))) ?? ""
      const outputs = [
        ...text.matchAll(/^\s*output:\s*["']?([^\s"'#]+)/gm),
      ].map((m) => rel(m[1]))
      out.push({
        tool: "swiftgen",
        label: "SwiftGen",
        root: root.dir,
        file: at("swiftgen.yml"),
        outputs: [...new Set(outputs)],
        command: "swiftgen",
      })
    }
    // Sourcery.
    if (tracked.has(at(".sourcery.yml"))) {
      const text = (await input.read(at(".sourcery.yml"))) ?? ""
      const outputs = [
        ...text.matchAll(/^\s*output:\s*["']?([^\s"'#]+)/gm),
      ].map((m) => rel(m[1]))
      out.push({
        tool: "sourcery",
        label: "Sourcery",
        root: root.dir,
        file: at(".sourcery.yml"),
        outputs,
        command: "sourcery",
      })
    }
    // OpenAPI Generator.
    if (tracked.has(at("openapitools.json"))) {
      const text = (await input.read(at("openapitools.json"))) ?? ""
      const outputs = [...text.matchAll(/"output"\s*:\s*"([^"]+)"/g)].map((m) =>
        rel(m[1].replace(/^#\{cwd\}\//, ""))
      )
      out.push({
        tool: "openapi",
        label: "OpenAPI client",
        root: root.dir,
        file: at("openapitools.json"),
        outputs,
        command:
          scriptFor("openapi") ??
          "npx @openapitools/openapi-generator-cli generate",
      })
    }
    // Dart build_runner.
    if (root.ecosystems.includes("pub")) {
      const pubspec = (await input.read(at("pubspec.yaml"))) ?? ""
      if (/^\s+build_runner:/m.test(pubspec))
        out.push({
          tool: "build_runner",
          label: "Dart build_runner",
          root: root.dir,
          file: at("pubspec.yaml"),
          outputs: [],
          command: "dart run build_runner build --delete-conflicting-outputs",
        })
    }
    // Go generate directives.
    if (root.ecosystems.includes("go")) {
      out.push({
        tool: "go-generate",
        label: "go generate",
        root: root.dir,
        file: at("go.mod"),
        outputs: [],
        command: "go generate ./...",
      })
    }
    // Rails schema dump, Tapioca RBIs, Laravel IDE helpers.
    if (root.ecosystems.includes("bundler")) {
      for (const dump of ["db/schema.rb", "db/structure.sql"])
        if (tracked.has(at(dump)))
          out.push({
            tool: "rails-schema",
            label: "Rails schema dump",
            root: root.dir,
            file: at(dump),
            outputs: [at(dump)],
            command: "bin/rails db:schema:dump",
            needs: "a running development database",
          })
      if (input.tracked.some((f) => f.startsWith(at("sorbet/rbi/"))))
        out.push({
          tool: "tapioca",
          label: "Sorbet RBIs (Tapioca)",
          root: root.dir,
          file: at("sorbet/tapioca/config.yml"),
          outputs: [at("sorbet/rbi/gems"), at("sorbet/rbi/dsl")],
          command: "bin/tapioca gems",
        })
    }
    if (root.ecosystems.includes("composer")) {
      const helpers = input.tracked.filter(
        (f) =>
          under(root.dir, f) &&
          /(^|\/)_ide_helper(_models)?\.php$|\.phpstorm\.meta\.php$/.test(f)
      )
      if (helpers.length)
        out.push({
          tool: "ide-helper",
          label: "Laravel IDE helpers",
          root: root.dir,
          file: at("composer.json"),
          outputs: helpers,
          command: "php artisan ide-helper:generate",
        })
    }
    // Gradle's OpenAPI Generator plugin writes sources its task regenerates.
    if (root.ecosystems.includes("gradle")) {
      const gradleFiles = input.tracked
        .filter(
          (f) => under(root.dir, f) && /(^|\/)build\.gradle(\.kts)?$/.test(f)
        )
        .slice(0, 12)
      for (const file of gradleFiles) {
        if (!/org\.openapi\.generator/.test((await input.read(file)) ?? ""))
          continue
        const wrapper = tracked.has(at("gradlew")) ? "./gradlew" : "gradle"
        out.push({
          tool: "openapi-gradle",
          label: "the OpenAPI Generator Gradle task",
          root: root.dir,
          file,
          outputs: [],
          command: `${wrapper} openApiGenerate`,
          fromScript: true,
        })
        break
      }
    }
    // Local pre-commit hooks that generate files.
    const preCommit = at(".pre-commit-config.yaml")
    if (tracked.has(preCommit)) {
      for (const hook of preCommitGenerators(
        (await input.read(preCommit)) ?? ""
      )) {
        out.push({
          tool: `pre-commit:${hook.id}`,
          label: `the ${hook.name ?? hook.id} pre-commit hook`,
          root: root.dir,
          file: preCommit,
          outputs: [],
          command: hook.entry,
          fromScript: true,
          everyCommit: hook.alwaysRun,
        })
      }
    }
    // Package scripts and Makefile targets that generate, for pairing.
    for (const [name, body] of Object.entries(s)) {
      if (!GENERATOR_SCRIPT.test(name)) continue
      const tool =
        TOOL_IN_SCRIPT.find((t) => t.re.test(body))?.tool ?? `script:${name}`
      if (out.some((c) => c.root === root.dir && c.tool === tool)) continue
      out.push({
        tool,
        label: `the ${name} script`,
        root: root.dir,
        file: at("package.json"),
        outputs: [],
        command: `${runner(root)} ${name}`,
        fromScript: true,
      })
    }
    if (root.files.includes("Makefile")) {
      for (const target of makeTargets(await input.read(at("Makefile")))) {
        if (!GENERATOR_SCRIPT.test(target)) continue
        out.push({
          tool: `make:${target}`,
          label: `make ${target}`,
          root: root.dir,
          file: at("Makefile"),
          outputs: [],
          command: `make ${target}`,
          fromScript: true,
        })
      }
    }
  }
  return out
}

// Collapse generated files into globs: each file's deepest directory whose
// tracked files are all generated becomes "dir/**" (merged upward only when a
// fully-generated parent holds several of them); the rest stay as paths. The
// deepest directory keeps the rule from covering hand-written files added
// beside it later.
export function collapse(files: string[], tracked: string[]): string[] {
  const generated = new Set(files)
  const counts = new Map<string, { all: number; gen: number }>()
  for (const file of tracked) {
    let dir = path.posix.dirname(file)
    while (dir && dir !== ".") {
      const entry = counts.get(dir) ?? { all: 0, gen: 0 }
      entry.all++
      if (generated.has(file)) entry.gen++
      counts.set(dir, entry)
      dir = path.posix.dirname(dir)
    }
  }
  const full = (dir: string) => {
    const c = counts.get(dir)
    return !!c && c.all === c.gen
  }
  const chosen = new Set<string>()
  const rest: string[] = []
  for (const file of files) {
    const dir = path.posix.dirname(file)
    if (dir !== "." && full(dir) && (counts.get(dir)?.all ?? 0) >= 2)
      chosen.add(dir)
    else rest.push(file)
  }
  // Merge siblings into a fully-generated parent.
  let merged = true
  while (merged) {
    merged = false
    const byParent = new Map<string, string[]>()
    for (const dir of chosen) {
      const parent = path.posix.dirname(dir)
      if (parent === ".") continue
      byParent.set(parent, [...(byParent.get(parent) ?? []), dir])
    }
    for (const [parent, children] of byParent) {
      if (children.length < 2 || !full(parent)) continue
      children.forEach((c) => chosen.delete(c))
      chosen.add(parent)
      merged = true
    }
  }
  return [...[...chosen].sort().map((d) => `${d}/**`), ...rest].slice(0, 40)
}

function globMatches(file: string, glob: string) {
  return path.posix.matchesGlob(file, glob)
}

export async function discoverGenerated(
  input: GeneratedInput
): Promise<GeneratedGroup[]> {
  const groups: GeneratedGroup[] = []
  const tracked = input.tracked
  const trackedSet = new Set(tracked)

  // Lockfiles: regenerate with the manager instead of merging by hand.
  for (const root of input.roots) {
    const ctx = input.contexts.get(root.dir)
    if (!ctx) continue
    for (const id of root.ecosystems) {
      const recipe = RECIPES[id]
      const lockfiles = recipe.lockfiles.filter((l) =>
        trackedSet.has(path.posix.join(root.dir, l))
      )
      if (!lockfiles.length || !recipe.lockRegen) continue
      const command = recipe.lockRegen(ctx)
      if (!command) continue
      groups.push({
        key: `generated:lock:${path.posix.join(root.dir, lockfiles[0])}`,
        label: `${lockfiles[0]} (${id} lockfile)`,
        root: root.dir,
        paths: lockfiles.map((l) => path.posix.join(root.dir, l)),
        command: inRoot(root.dir, command),
        confidence: "verified",
        evidence: lockfiles.map((l) => ({
          kind: "file" as const,
          label: `${l} is tracked`,
          path: path.posix.join(root.dir, l),
        })),
        lockfile: true,
      })
    }
    // pip-compile outputs are the Python "lockfile".
    if (root.ecosystems.includes("pip") && ctx) {
      const command = RECIPES.pip.lockRegen?.(ctx)
      const reqs = root.files.filter((f) => /^requirements.*\.txt$/.test(f))
      if (command && reqs.length)
        groups.push({
          key: `generated:lock:${path.posix.join(root.dir, reqs[0])}`,
          label: "compiled requirements",
          root: root.dir,
          paths: reqs.map((r) => path.posix.join(root.dir, r)),
          command: inRoot(root.dir, command),
          confidence: "verified",
          evidence: [
            {
              kind: "file",
              label: `${reqs[0]} has a pip-compile header`,
              path: path.posix.join(root.dir, reqs[0]),
            },
          ],
          lockfile: true,
        })
    }
  }
  const lockPaths = new Set(groups.flatMap((g) => g.paths))

  // .gitattributes linguist-generated.
  const attributeGlobs: Array<{ glob: string; file: string }> = []
  for (const file of tracked.filter((f) => /(^|\/)\.gitattributes$/.test(f))) {
    const base =
      path.posix.dirname(file) === "." ? "" : path.posix.dirname(file)
    for (const line of ((await input.read(file)) ?? "").split("\n")) {
      const [pattern, ...attrs] = line.trim().split(/\s+/)
      if (!pattern || pattern.startsWith("#")) continue
      if (
        !attrs.some(
          (a) =>
            a === "linguist-generated" ||
            a === "linguist-generated=true" ||
            a === "-diff"
        )
      )
        continue
      const glob = pattern.includes("/")
        ? path.posix.join(base, pattern.replace(/^\//, ""))
        : path.posix.join(base, "**", pattern)
      attributeGlobs.push({ glob, file })
    }
  }

  // Header markers and known suffixes.
  const marked = new Map<string, string>()
  const strongMarks = new Set<string>()
  const suffixHits = new Map<
    string,
    { glob: string; label: string; tool: string; files: string[] }
  >()
  let scanned = 0
  for (const file of tracked) {
    if (lockPaths.has(file)) continue
    const suffix = SUFFIXES.find((s) => s.re.test(file))
    if (suffix) {
      const root = rootFor(input.roots, file)
      const key = `${root}|${suffix.glob}`
      const hit = suffixHits.get(key) ?? {
        glob: suffix.glob,
        label: suffix.label,
        tool: suffix.tool,
        files: [],
      }
      hit.files.push(file)
      suffixHits.set(key, hit)
      continue
    }
    if (!TEXT_EXT.test(file) || scanned >= MAX_HEADER_SCANS) continue
    scanned++
    const head = ((await input.read(file)) ?? "").slice(0, HEADER_BYTES)
    const marker = MARKERS.find((m) => m.re.test(head))
    if (marker && !/autogenerated by (pip-compile|uv)/i.test(head)) {
      marked.set(file, marker.label)
      if (marker.strong) strongMarks.add(file)
    }
  }

  const configs = await toolConfigs(input)
  const configFor = (root: string, tool: string) =>
    configs.find((c) => c.root === root && c.tool === tool) ??
    configs.find((c) => c.tool === tool)

  // Co-change: how often a path changed in the same commit as a config.
  const cochange = (paths: string[], configFile: string) =>
    input.history.filter(
      (commit) =>
        commit.includes(configFile) &&
        commit.some((f) => paths.some((p) => globMatches(f, p) || f === p))
    ).length

  // Tool configs with declared outputs.
  const claimed = new Set<string>()
  for (const config of configs) {
    if (!config.outputs.length) continue
    const files = tracked.filter((f) =>
      config.outputs.some(
        (o) => f === o || f.startsWith(`${o.replace(/\/$/, "")}/`)
      )
    )
    if (!files.length) continue
    files.forEach((f) => claimed.add(f))
    const globs = config.outputs.map((o) =>
      tracked.includes(o) ? o : `${o.replace(/\/$/, "")}/**`
    )
    const together = cochange(globs, config.file)
    groups.push({
      key: `generated:${config.tool}:${config.root || "."}`,
      label: config.label,
      root: config.root,
      paths: globs,
      command: config.command ? inRoot(config.root, config.command) : null,
      confidence: config.needs ? "likely" : "verified",
      evidence: [
        {
          kind: "file",
          label: `${config.file} writes ${config.outputs.join(", ")}`,
          path: config.file,
        },
        ...(together
          ? [
              {
                kind: "history" as const,
                label: `Changed together with ${config.file} in ${together} recent commits`,
              },
            ]
          : []),
      ],
      ...(config.needs ? { needs: config.needs } : {}),
    })
  }

  // Known suffixes.
  for (const [key, hit] of suffixHits) {
    const root = key.split("|")[0]
    const files = hit.files.filter((f) => !claimed.has(f))
    if (!files.length) continue
    files.forEach((f) => claimed.add(f))
    const config = configFor(root, hit.tool)
    const glob = root ? path.posix.join(root, hit.glob) : hit.glob
    const command =
      config?.command ??
      (hit.tool === "tsr"
        ? "npx tsr generate"
        : hit.tool === "next"
          ? null
          : hit.tool === "dotnet"
            ? "dotnet build"
            : null)
    groups.push({
      key: `generated:${hit.tool}:${root || "."}`,
      label: hit.label,
      root,
      paths: [glob],
      command: command ? inRoot(config?.root ?? root, command) : null,
      confidence: command ? (config ? "verified" : "likely") : "likely",
      evidence: [
        {
          kind: "file",
          label: `${files.length} tracked file${files.length === 1 ? "" : "s"} like ${files[0]}`,
          path: files[0],
        },
        ...(config
          ? [
              {
                kind: "file" as const,
                label: `${config.label} is configured in ${config.file}`,
                path: config.file,
              },
            ]
          : []),
      ],
    })
  }

  // Lock-step churn: a directory whose files change together in most
  // commits (an index or snapshot a hook refreshes on every commit). Only
  // data-like directories, never plain source.
  const CODE =
    /\.(py|pyi|ts|tsx|js|jsx|mjs|cjs|go|rs|java|kt|kts|cs|swift|m|c|cc|cpp|h|hpp|php|rb|dart|vue|svelte)$/
  const commits = input.history.filter((c) => c.length)
  if (commits.length >= 8) {
    const dirFiles = new Map<string, string[]>()
    for (const file of tracked) {
      const dir = path.posix.dirname(file)
      if (dir === "." || dir.split("/").length > 3 || lockPaths.has(file))
        continue
      dirFiles.set(dir, [...(dirFiles.get(dir) ?? []), file])
    }
    for (const [dir, files] of dirFiles) {
      if (
        files.length < 2 ||
        files.length > 200 ||
        files.some((f) => claimed.has(f))
      )
        continue
      const code = files.filter((f) => CODE.test(f)).length
      if (
        code / files.length >= 0.5 &&
        !path.posix.basename(dir).startsWith(".")
      )
        continue
      const touching = commits.filter((c) =>
        c.some((f) => f.startsWith(`${dir}/`))
      )
      if (touching.length < 5 || touching.length / commits.length < 0.25)
        continue
      // Nobody edits an index by hand: it changes alongside other files,
      // (almost) never on its own.
      const alone = touching.filter((c) =>
        c.every((f) => f.startsWith(`${dir}/`))
      ).length
      if (alone / touching.length > 0.1) continue
      const together =
        touching.reduce(
          (sum, c) =>
            sum + files.filter((f) => c.includes(f)).length / files.length,
          0
        ) / touching.length
      if (together < 0.6) continue
      files.forEach((f) => claimed.add(f))
      const root = rootFor(input.roots, files[0])
      const hook =
        configs.find((c) => c.everyCommit && c.root === root) ??
        configs.find((c) => c.everyCommit)
      const pairing = hook
        ? {
            command: inRoot(hook.root, hook.command!),
            evidence: {
              kind: "manifest" as const,
              label: `${hook.label} runs on every commit`,
              path: hook.file,
            },
          }
        : pairCommand(root, [`${dir}/**`], configs, cochange, input.roots)
      groups.push({
        key: `generated:churn:${dir}`,
        label: `${dir}/`,
        root,
        paths: [`${dir}/**`],
        command: pairing?.command ?? null,
        confidence: "likely",
        evidence: [
          {
            kind: "history",
            label: `${files.length} files in ${dir}/ changed together in ${touching.length} of the last ${commits.length} commits`,
          },
          ...files
            .filter((f) => marked.has(f))
            .slice(0, 2)
            .map((f) => ({
              kind: "file" as const,
              label: `${f} has ${marked.get(f)}`,
              path: f,
            })),
          ...(pairing ? [pairing.evidence] : []),
        ],
      })
    }
  }

  // Header-marked files, grouped per root, plus .gitattributes globs.
  const byRoot = new Map<string, string[]>()
  for (const file of marked.keys()) {
    if (claimed.has(file)) continue
    const root = rootFor(input.roots, file)
    byRoot.set(root, [...(byRoot.get(root) ?? []), file])
  }
  for (const { glob, file } of attributeGlobs) {
    const matches = tracked.filter(
      (f) => globMatches(f, glob) && !claimed.has(f) && !lockPaths.has(f)
    )
    if (!matches.length) continue
    matches.forEach((f) => claimed.add(f))
    const root = rootFor(input.roots, matches[0])
    const pairing = pairCommand(root, [glob], configs, cochange, input.roots)
    groups.push({
      key: `generated:attributes:${glob}`,
      label: "files marked generated in .gitattributes",
      root,
      paths: [glob],
      command: pairing?.command ?? null,
      confidence: pairing ? "likely" : "verified",
      evidence: [
        {
          kind: "file",
          label: `${file} marks ${glob} as generated`,
          path: file,
        },
        ...(pairing ? [pairing.evidence] : []),
      ],
    })
  }
  for (const [root, files] of byRoot) {
    const remaining = files.filter((f) => !claimed.has(f))
    if (!remaining.length) continue
    const globs = collapse(
      remaining,
      tracked.filter((f) => under(root, f))
    )
    const goMarked = remaining.every(
      (f) => marked.get(f) === "Go generated-code marker"
    )
    const pairing = goMarked
      ? {
          command: inRoot(root, "go generate ./..."),
          evidence: {
            kind: "file" as const,
            label: "Go files carry the standard generated-code marker",
          },
        }
      : pairCommand(root, globs, configs, cochange, input.roots)
    const labels = [...new Set(remaining.map((f) => marked.get(f)!))]
    groups.push({
      key: `generated:marked:${root || "."}:${globs[0]}`,
      label: goMarked ? "go generate" : "files with a generated-code header",
      root,
      paths: globs,
      command: pairing?.command ?? null,
      confidence:
        pairing || !remaining.every((f) => strongMarks.has(f))
          ? "likely"
          : "verified",
      evidence: [
        {
          kind: "file",
          label: `${remaining.length} tracked file${remaining.length === 1 ? "" : "s"} with a ${labels[0]}${labels.length > 1 ? " (and others)" : ""}, e.g. ${remaining[0]}`,
          path: remaining[0],
        },
        ...(pairing ? [pairing.evidence] : []),
      ],
    })
  }
  return mergeByCommand(groups)
}

// The command for outputs no config declares: the root's only generator
// script, or the config they keep changing together with.
function pairCommand(
  root: string,
  globs: string[],
  configs: ToolConfig[],
  cochange: (paths: string[], configFile: string) => number,
  roots: ProjectRoot[]
): { command: string; evidence: Omit<Evidence, "id"> } | null {
  const candidates = configs.filter((c) => c.root === root && c.command)
  let best: { config: ToolConfig; together: number } | null = null
  for (const config of candidates) {
    const together = cochange(globs, config.file)
    if (together >= 2 && (!best || together > best.together))
      best = { config, together }
  }
  if (best)
    return {
      command: inRoot(best.config.root, best.config.command!),
      evidence: {
        kind: "history",
        label: `Changed together with ${best.config.file} in ${best.together} recent commits`,
      },
    }
  const scripts = candidates.filter((c) => c.fromScript)
  if (scripts.length === 1 && roots.some((r) => r.dir === root))
    return {
      command: inRoot(root, scripts[0].command!),
      evidence: {
        kind: "manifest",
        label: `${scripts[0].label} is the project's only generator script`,
        path: scripts[0].file,
      },
    }
  return null
}

// Groups regenerated by the same command become one rule.
function mergeByCommand(groups: GeneratedGroup[]): GeneratedGroup[] {
  const out: GeneratedGroup[] = []
  for (const group of groups) {
    const same =
      group.command && !group.lockfile
        ? out.find((g) => g.command === group.command && !g.lockfile)
        : null
    if (!same) {
      out.push({ ...group, paths: [...new Set(group.paths)] })
      continue
    }
    same.paths = [...new Set([...same.paths, ...group.paths])]
    same.evidence = [...same.evidence, ...group.evidence].slice(0, 8)
    if (group.confidence === "verified" && same.confidence !== "verified")
      same.confidence = group.confidence
  }
  return out
}
