import { existsSync } from "fs"
import { mkdir, mkdtemp, readFile, realpath, rm, writeFile } from "fs/promises"
import { tmpdir } from "os"
import { join } from "path"
import { pathToFileURL } from "url"
import type { PlaywrightCheck } from "./checks-manifest"
import { CommandError, runLongCommand } from "./long-command"
import {
  nodeCommand,
  nodeEnv,
  requestTestBrowser,
  resolvePlaywright,
  testBrowserForRun,
  type PlaywrightInstall,
  type TestBrowser,
} from "./playwright-install"

// Runs one `runner: "playwright"` check (plan 109.06). The model never invokes
// Playwright: it names a spec in the manifest and calls run_checks. Each run
// gets a generated config in a temp directory (never in the workspace) that
// points at the checks directory, selects the story's tag, writes traces and
// screenshots of failures into the step's evidence directory, and reports
// JSON the harness parses into per-test results.

export interface PlaywrightTestResult {
  // Describe blocks and test title, joined with " › ".
  title: string
  // Relative to the checks directory.
  file: string
  status: "passed" | "failed" | "timedOut" | "skipped" | "interrupted"
  durationMs: number
  error?: string
}

export interface PlaywrightRun {
  passed: boolean
  exitCode: number | null
  timedOut: boolean
  output: string
  tests: PlaywrightTestResult[]
  // Traces and screenshots of failures, in the evidence directory.
  artifacts: string[]
  // Set when the check couldn't run for a reason that isn't the app's fault
  // (no browser installed yet): the check is not verifiable, not failed.
  notVerifiable: string | null
  runner: {
    source: PlaywrightInstall["source"]
    version: string
    browser: "workspace" | TestBrowser["kind"]
  }
}

const CONFIG_NAMES = [
  "playwright.config.ts",
  "playwright.config.mts",
  "playwright.config.cts",
  "playwright.config.js",
  "playwright.config.mjs",
  "playwright.config.cjs",
]

function escapeRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

// The tests a check runs: the story's tag, and the check's own grep on top.
export function checkGrep(storyRef: string, grep?: string): string {
  const tag = `(?=.*@${escapeRegExp(storyRef)}(?![\\w.]))`
  return grep ? `^${tag}(?=.*(?:${grep}))` : `^${tag}`
}

// The spec file as a testMatch pattern: its path inside the checks
// directory, with either separator.
export function specPattern(spec: string): string {
  return `(?:^|[\\\\/])${spec.split("/").map(escapeRegExp).join("[\\\\/]")}$`
}

// The generated config: the workspace's own config (when its Playwright is
// used and it has one) merged under the harness's settings. Its projects and
// webServer are dropped: the harness picks the browser and starts the app.
export function buildPlaywrightConfig(input: {
  testDir: string
  spec: string
  grep: string
  outputDir: string
  reportFile: string
  baseURL: string | null
  channel: "chrome" | null
  baseConfig: string | null
}): string {
  const json = (value: unknown) => JSON.stringify(value)
  const use = [
    "...(base.use ?? {})",
    ...(input.baseURL ? [`baseURL: ${json(input.baseURL)}`] : []),
    ...(input.channel ? [`channel: ${json(input.channel)}`] : []),
    `trace: "retain-on-failure"`,
    `screenshot: "only-on-failure"`,
  ]
  return [
    "// Generated by North Star for one QA check run (plan 109.06).",
    ...(input.baseConfig
      ? [
          `import * as baseModule from ${json(pathToFileURL(input.baseConfig).href)}`,
          // A CommonJS config arrives wrapped in one or two `default`s.
          "let base = baseModule",
          'while (base && typeof base === "object" && "default" in base) base = base.default',
        ]
      : ["const base = {}"]),
    "const {",
    "  projects, webServer, testDir, testMatch, testIgnore, outputDir,",
    "  reporter, grep, grepInvert, retries, ...rest",
    "} = base",
    "export default {",
    "  ...rest,",
    `  testDir: ${json(input.testDir)},`,
    `  testMatch: new RegExp(${json(specPattern(input.spec))}),`,
    `  grep: new RegExp(${json(input.grep)}),`,
    // run_checks retries a failed check once itself and records both.
    "  retries: 0,",
    `  outputDir: ${json(input.outputDir)},`,
    `  reporter: [["json", { outputFile: ${json(input.reportFile)} }], ["line"]],`,
    `  use: { ${use.join(", ")} },`,
    "}",
    "",
  ].join("\n")
}

// Loaded into the runner and its workers (NODE_OPTIONS --require).
//
// With the bundled runner, a spec's `import "@playwright/test"` that the
// workspace can't resolve resolves to the bundled copy. NODE_PATH covers
// require(); this covers ESM imports, which ignore NODE_PATH.
//
// In a child the runner forked (a worker, where tests run; it has an IPC
// channel, the runner itself doesn't), the variables that make Electron run
// as Node are dropped once loaded: a worker forks nothing that needs them,
// and an Electron app a test starts with _electron.launch would inherit them
// and run as Node instead of as the app.
export const RUNNER_HOOK = `const { registerHooks } = require("node:module")
const { pathToFileURL } = require("node:url")
const { join } = require("node:path")
const root = process.env.NORTH_STAR_PLAYWRIGHT_MODULES
if (typeof process.send === "function") {
  for (const name of ["ELECTRON_RUN_AS_NODE", "NODE_OPTIONS", "NODE_PATH", "NORTH_STAR_PLAYWRIGHT_MODULES"])
    delete process.env[name]
}
if (registerHooks && root) {
  const parentURL = pathToFileURL(join(root, "_.js")).href
  registerHooks({
    resolve(specifier, context, next) {
      try {
        return next(specifier, context)
      } catch (err) {
        if (/^(@playwright\\/test|playwright)(\\/|$)/.test(specifier))
          return next(specifier, { ...context, parentURL })
        throw err
      }
    },
  })
}
`

interface JsonResult {
  status?: string
  duration?: number
  errors?: Array<{ message?: string }>
  error?: { message?: string }
  attachments?: Array<{ path?: string }>
}
interface JsonSuite {
  title?: string
  file?: string
  specs?: Array<{
    title?: string
    file?: string
    tests?: Array<{ results?: JsonResult[] }>
  }>
  suites?: JsonSuite[]
}

const ANSI = /\u001b\[[0-9;]*m/g

function clip(text: string, chars = 600): string {
  const clean = text.replace(ANSI, "").trim()
  return clean.length > chars ? `${clean.slice(0, chars)}…` : clean
}

// Per-test results and failure artifacts from Playwright's JSON report.
export function parsePlaywrightReport(text: string): {
  tests: PlaywrightTestResult[]
  artifacts: string[]
  errors: string[]
} {
  const report = JSON.parse(text) as {
    suites?: JsonSuite[]
    errors?: Array<{ message?: string }>
  }
  const tests: PlaywrightTestResult[] = []
  const artifacts: string[] = []
  const walk = (suite: JsonSuite, titles: string[]) => {
    // The file's own suite is titled with the file name: not a describe.
    const path =
      suite.title && suite.title !== suite.file
        ? [...titles, suite.title]
        : titles
    for (const spec of suite.specs ?? [])
      for (const test of spec.tests ?? []) {
        const result = test.results?.[test.results.length - 1]
        const status = (result?.status ??
          "skipped") as PlaywrightTestResult["status"]
        const message = result?.error?.message ?? result?.errors?.[0]?.message
        tests.push({
          title: [...path, spec.title ?? ""].filter(Boolean).join(" › "),
          file: spec.file ?? suite.file ?? "",
          status,
          durationMs: result?.duration ?? 0,
          ...(message && status !== "passed" ? { error: clip(message) } : {}),
        })
        for (const r of test.results ?? [])
          for (const a of r.attachments ?? [])
            if (a.path && !artifacts.includes(a.path)) artifacts.push(a.path)
      }
    for (const child of suite.suites ?? []) walk(child, path)
  }
  for (const suite of report.suites ?? []) walk(suite, [])
  return {
    tests,
    artifacts,
    errors: (report.errors ?? [])
      .map((e) => clip(e.message ?? ""))
      .filter(Boolean),
  }
}

const MISSING_BROWSER =
  /Executable doesn't exist|browserType\.launch: .*(not found|install)/i

function workspaceConfig(cwd: string): string | null {
  for (const name of CONFIG_NAMES)
    if (existsSync(join(cwd, name))) return join(cwd, name)
  return null
}

export async function runPlaywrightCheck(input: {
  // Absolute paths: the check's folder and the checks directory.
  cwd: string
  checksDir: string
  storyRef: string
  check: PlaywrightCheck
  // The check's services (BASE_URL, APP_<KEY>_URL, …).
  env: Record<string, string>
  // Where traces and screenshots of failures go.
  outputDir: string
  signal?: AbortSignal
}): Promise<PlaywrightRun> {
  const install = resolvePlaywright(input.cwd)
  if (!install)
    return {
      passed: false,
      exitCode: null,
      timedOut: false,
      output: "",
      tests: [],
      artifacts: [],
      notVerifiable:
        "Playwright isn't available: the workspace has no @playwright/test and the bundled copy is missing. Reinstall North Star.",
      runner: { source: "bundled", version: "none", browser: "missing" },
    }
  const browser: TestBrowser | null =
    install.source === "bundled" ? await testBrowserForRun() : null
  const scratch = await mkdtemp(join(tmpdir(), "north-star-playwright-"))
  try {
    const reportFile = join(scratch, "report.json")
    const configFile = join(scratch, "playwright.config.mjs")
    await mkdir(input.outputDir, { recursive: true })
    await writeFile(
      configFile,
      buildPlaywrightConfig({
        // Real, so the report's file paths are relative to it.
        testDir: await realpath(input.checksDir).catch(() => input.checksDir),
        spec: input.check.spec,
        grep: checkGrep(input.storyRef, input.check.grep),
        outputDir: input.outputDir,
        reportFile,
        baseURL: input.env.BASE_URL ?? null,
        channel: browser?.kind === "chrome" ? "chrome" : null,
        baseConfig:
          install.source === "workspace" ? workspaceConfig(input.cwd) : null,
      })
    )
    const hook = join(scratch, "runner-hook.cjs")
    await writeFile(hook, RUNNER_HOOK)
    const runnerEnv: Record<string, string> = {
      NODE_OPTIONS: `--require "${hook.replace(/\\/g, "/")}"`,
    }
    if (install.source === "bundled") {
      Object.assign(runnerEnv, {
        NODE_PATH: install.nodeModules!,
        NORTH_STAR_PLAYWRIGHT_MODULES: install.nodeModules!,
      })
      if (browser && browser.kind !== "chrome" && browser.browsersPath)
        runnerEnv.PLAYWRIGHT_BROWSERS_PATH = browser.browsersPath
    }
    const env = nodeEnv({
      // CI keeps Playwright non-interactive and off the HTML report server.
      CI: "1",
      FORCE_COLOR: "0",
      ...input.env,
      ...runnerEnv,
    })
    let exitCode: number | null = 0
    let timedOut = false
    let output = ""
    try {
      const { stdout, stderr } = await runLongCommand(
        nodeCommand(install.cliPath, ["test", "--config", configFile]),
        {
          cwd: input.cwd,
          env,
          quietLimitMs: input.check.timeoutMs,
          overallLimitMs: input.check.timeoutMs,
          signal: input.signal,
        }
      )
      output = `${stdout}\n${stderr}`
    } catch (err) {
      const failed = err instanceof CommandError ? err : null
      exitCode = failed?.code ?? null
      timedOut =
        failed?.stoppedFor === "quiet" || failed?.stoppedFor === "overall"
      output = failed
        ? `${failed.stdout}\n${failed.stderr}\n${failed.message}`
        : String(err)
    }
    let parsed: ReturnType<typeof parsePlaywrightReport> = {
      tests: [],
      artifacts: [],
      errors: [],
    }
    try {
      parsed = parsePlaywrightReport(await readFile(reportFile, "utf8"))
    } catch {
      // No report (Playwright didn't start, or was stopped): the output says why.
    }
    const ran = parsed.tests.filter((t) => t.status !== "skipped")
    const passed =
      exitCode === 0 &&
      ran.length > 0 &&
      ran.every((t) => t.status === "passed")
    const failures = [
      output,
      ...parsed.errors,
      ...parsed.tests.map((t) => t.error ?? ""),
    ].join("\n")
    let notVerifiable: string | null = null
    if (
      !passed &&
      browser?.kind === "missing" &&
      MISSING_BROWSER.test(failures)
    ) {
      requestTestBrowser()
      notVerifiable =
        "Browser not installed: there's no Chrome on this computer and the test browser hasn't been downloaded yet. The user is asked to allow a one-time download in Mission Control (or Settings → General → Browser); until then, record the criteria these checks cover as not verifiable."
    }
    if (
      !passed &&
      !timedOut &&
      exitCode !== null &&
      !ran.length &&
      !notVerifiable
    )
      output = `No test in ${input.check.spec} matched @${input.storyRef}${input.check.grep ? ` and grep "${input.check.grep}"` : ""}. Tag each test title with the story's tag.\n${output}`
    return {
      passed,
      exitCode,
      timedOut,
      output,
      tests: parsed.tests,
      artifacts: parsed.artifacts.filter((path) => existsSync(path)),
      notVerifiable,
      runner: {
        source: install.source,
        version: install.version,
        browser: browser ? browser.kind : "workspace",
      },
    }
  } finally {
    await rm(scratch, { recursive: true, force: true }).catch(() => {})
  }
}
